version: 2.1
orbs:
  node: circleci/node@4.0.0
  coveralls: coveralls/coveralls@1.0.4

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Run tests with JUnit as reporter
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - coveralls/upload
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}
    